#Node Port service for the Jenkins Deployment

apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui
  namespace: perf-platform
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080
      name: ui
      # NodePort can be replaced by the LoadBalancer
  selector:
    app: jenkins