# Persistent Volume Claim for Jenkins
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: perf-platform
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi